### ISSUE TITLE
Categorical variable

### ISSUE THREAD

**Issue by Shevchook** [nsgrantham/ggbraid#11]
Hi, Neal! I like your work. ggbraid package is really good. Didn't you consider categorical independent variable? When I put numbers instead of months it works seamlessly. But when I put names of months (as an ordered factor) it does not work. What did I do wrong?
Here is my data.
df_long <- tibble(
    x = c(month.abb, month.abb),
    y = c(57.6085, 47.78275, 50.84225, 47.7515, 51.35225, 44.7345, 45.33275, 
          44.57025, 42.1275, 50.073, 48.94750, 50.5105, 53.61, 47.128, 48.326,
          46.223, 44.68, 47.043, 47.297, 44.008, 48.372, 59.047, 63.438, 67.663),
    z = c(rep("Baseline", 12), rep("Current", 12))
)
df_long$x <- factor(df_long$x, levels = month.abb)

**Comment by nsgrantham** [comment]
Hi Pavlo!

I think I've fixed it. Download the latest version of ggbraid (0.2.1) and give the following code a try:

```r
library(ggplot2)
library(ggbraid)
library(tidyr)
library(tibble)

df_long <- tibble(
  x = c(month.abb, month.abb),
  y = c(57.6085, 47.78275, 50.84225, 47.7515, 51.35225, 44.7345, 45.33275,
    44.57025, 42.1275, 50.073, 48.94750, 50.5105, 53.61, 47.128, 48.326,
    46.223, 44.68, 47.043, 47.297, 44.008, 48.372, 59.047, 63.438, 67.663),
  z = c(rep("Baseline", 12), rep("Current", 12))
)

df_long$x <- factor(df_long$x, levels = month.abb)
df_wide <- pivot_wider(df_long, names_from = z, values_from = y)

ggplot() +
  geom_line(aes(x, y, group = z, linetype = z), data = df_long) +
  geom_braid(aes(x, ymin = Baseline, ymax = Current), data = df_wide, alpha = 0.4)
```
![](https://user-images.githubusercontent.com/4433521/165450683-e4c35ce2-2c62-4589-8cc0-35009459a1ed.png)

```r
ggplot() +
  geom_line(aes(x, y, group = z, linetype = z), data = df_long) +
  geom_braid(
    aes(x, ymin = Baseline, ymax = Current, fill = Baseline < Current),
    data = df_wide,
    alpha = 0.4
  )
```
![](https://user-images.githubusercontent.com/4433521/165450692-2af01251-278d-4351-a8dd-a314b26ca4e7.png)

Can you confirm that everything works correctly now?

**Comment by Shevchook** [comment]
Great! Thank you! I replicated it already.

27 квітня 2022, 09:01:10, від "Neal Grantham" ***@***.***>:


Hi Pavlo!
I think I've fixed it. Download the latest version of ggbraid (0.2.1) and give the following code a try:
library(ggplot2)
library(ggbraid)
library(tidyr)
library(tibble)

df_long <- tibble(
  x = c(month.abb, month.abb),
  y = c(57.6085, 47.78275, 50.84225, 47.7515, 51.35225, 44.7345, 45.33275,
    44.57025, 42.1275, 50.073, 48.94750, 50.5105, 53.61, 47.128, 48.326,
    46.223, 44.68, 47.043, 47.297, 44.008, 48.372, 59.047, 63.438, 67.663),
  z = c(rep("Baseline", 12), rep("Current", 12))
)

df_long$x <- factor(df_long$x, levels = month.abb)
df_wide <- pivot_wider(df_long, names_from = z, values_from = y)

ggplot() +
  geom_line(aes(x, y, group = z, linetype = z), data = df_long) +
  geom_braid(aes(x, ymin = Baseline, ymax = Current), data = df_wide, alpha = 0.4)

ggplot() +
  geom_line(aes(x, y, group = z, linetype = z), data = df_long) +
  geom_braid(
    aes(x, ymin = Baseline, ymax = Current, fill = Baseline < Current),
    data = df_wide,
    alpha = 0.4
  )

Can you confirm that everything works correctly now?

**Comment by nsgrantham** [comment]
Great, thanks for using the package. Happy braiding!

**Comment by Shevchook** [comment]
I'll keep you posted. Good night!
Pavlo.

27 квітня 2022, 09:11:58, від "Neal Grantham" ***@***.***>:


Great, thanks for using the package. Happy braiding!
